# Generated by Django 4.1.3 on 2023-05-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_paymentrequest_remove_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
