# Generated by Django 4.2.1 on 2023-05-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_paymentrequest_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='name',
            field=models.CharField(default='test name', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='address',
            field=models.CharField(default='test name', max_length=255),
            preserve_default=False,
        ),
    ]
